### ISSUE TITLE
Not sure if this is any use to you

### ISSUE THREAD

**Issue by strayr** [treeific/3D_Printer#1]
https://github.com/VoronDesign/VoronUsers/tree/master/printer_mods/strayr/stealthburner_creality_toolhead

It's in in use printing abs skirts with a 0.6 right now.

Also i added your complete parts to https://github.com/SW-Conversion/mod-regisistry

**Comment by treeific** [comment]
Very cool, thanks for including it.

Also thanks for providing the tool head. I made the mistake of designing mine, and then searching if it was already designed... Lol

I'll try to consolidate at some point, I might remove mine and link to yours
